### ISSUE TITLE
alternitives to web3.js

### ISSUE THREAD

**Issue by jvluso** [aragon/radspec#85]
Web3.js is a very large dependency. It would be nice for some applications, like frame and for a radspec metamask plugin to not need it. Would you be interested in a refactor of radspec that uses an alternative like ethers.js instead of web3?

**Comment by sohkai** [comment]
I'm not sure ethers.js would be any smaller and in fact... quite a large portion of the dependency size already comes from ethers.js due to web3.js@1 now relying on ethers' abi module (see https://bundlephobia.com/result?p=radspec@1.6.1).

We only really use the abi encoder, some utils, and web3.eth.call, so we may be have to shave some size off.

**Comment by sohkai** [comment]
Closing for now; we will evaluate moving to ethers in the future.
